### ISSUE TITLE
Plugin freezes Obsidian

### ISSUE THREAD

**Issue by RomanRcT** [konodyuk/obsidian-text-expander#1]
After enabling plugin Obsidian doesn't respond. After killing app the plugin remains disabled. Obsidian v. 0.10,7

**Comment by konodyuk** [comment]
Hi @RomanRcT, could you please provide some additional information? In particular, I need your OS and plugin settings: shortcuts (if not default) and "shell executable".

**Comment by dummifiedme** [comment]
+1
Facing the same issue.
Tried to enable the plugin, the obsidian froze and never returned back.
![image](https://user-images.githubusercontent.com/68785729/104843925-2a01f280-58f3-11eb-9de9-81e21a27cef3.png)

Even the button, as you can see, is not coloured as "On". Its just grey.

Requires force close to bring back Obsidian.

**Comment by konodyuk** [comment]
@RomanRcT @dummifiedme I think I fixed it in the 1.0.1 release. Please let me know if updating resolves the issue.

**Comment by dummifiedme** [comment]
Yes, it is fixed :) Thanks

**Comment by RomanRcT** [comment]
> @RomanRcT @dummifiedme I think I fixed it in the 1.0.1 release. Please let me know if updating resolves the issue.

The issue is fixed with the new version.
