### ISSUE TITLE
information about missing windows support is hidden

### ISSUE THREAD

**Issue by Vinzent03** [konodyuk/obsidian-text-expander#2]
Your plugin looks really interesting, but I am on windows, so I cant use it right now. But it would be really helpful if you wouldn't place that information at the very bottom of the README. I was already thinking of some use cases, until I found that comment. It would not suprise me, if some windows users create an issue, because the plugin is not working, if the information is so well hidden.

**Comment by konodyuk** [comment]
Sorry for the misleading readme. I pushed the warning to the very top of it, which I hope will prevent such cases in the future. In fact, the plugin supports windows to some extent: i.e. static replacements will work correctly if it is what you need. Using commands, however, is a bit more complicated, as you'll need to change the `Shell executable` setting to `powershell` and use Powershell syntax in all `command` fields. Another workaround could be to set `Shell executable` to `Python.exe C:\path\to\script.py` (or so) and parse the commands inside the `while True: print(process(input()))` loop in `script.py`.

**Comment by Vinzent03** [comment]
Thank you for the advice. I've set my Shell excectuable to your tip. 
My python file is only `print(input())`, and my command is
```json
{
"regex": "^test:",
"command": "<text>"
},
```
But nothing happens. Do you know whats wrong?

**Comment by konodyuk** [comment]
Please make sure the command you specified in `Shell executable` is correct and invokes the script if it is run in the real shell (`cmd.exe`). Also check that the content of `Shortcuts` field is a correct JSON list, which means that if `{'regex':'^test'...}` is the only entry, it should not end with a comma.

**Comment by Vinzent03** [comment]
Yes it is correct JSON.
Now my command is: 
```json
	{
		"regex": "^test:",
		"command": "python C:/Users/vinze/OneDrive/Schule/.obsidian/scripts/tool.py"
	},
```
My python file is only `print("testtesttest")`
My Shell executable is `powershell`
If I press Tab nothing happens. If I run the command anywhere in powershell it workes. The python file contains only a print, without input so this cant be the bug. I am getting no error on restart, as it was with other shell executables.

**Comment by konodyuk** [comment]
Does simple replacement work? E.g. `{'regex': '^test$', 'replacement': 'test_replacement'}`

**Comment by Vinzent03** [comment]
Yes it does. I think I will clone it and do some extra logging.

**Comment by Vinzent03** [comment]
The problem, why it did nothing is, is the `:` in `"test:"`. But it does still not work. Maybe this will change oneday.
