### ISSUE TITLE
Use different syntax for replacements

### ISSUE THREAD

**Issue by scriptmode** [konodyuk/obsidian-text-expander#3]
It would be nice to have a different syntax for calling replacements. 
I propose @trigger or ::trigger for this case, but if possible it should be configurable.

This would allow reusing trigger-words for different context. And this would give a mental context when something is a fast replacment or a potential slow call to an external process. For example, I use {{@py}} and {{@sh}} to insert code-fences for python- and shell-code, but typing this so often can be a pain.

**Comment by konodyuk** [comment]
Hello @scriptmode, thank you for the feedback. I've already added `:trigger` syntax support in [version 1.1.0](https://github.com/konodyuk/obsidian-text-expander/releases/tag/1.1.0). You can use either form (':eval:1+1' or `{{eval:1+1}}`) for any trigger, with only difference that in the former case, trigger cannot contain whitespace characters (in other words, if you attempt to evaluate `:long trigger` as a whole, only `:long` will be processed). In the case with code fences, `:@py` will do the same as `{{@py}}`.
If I get it right, you also request that different syntax invokes different commands. It can be implemented, but then the settings will become even more sophisticated, while my current effort is to simplify the interface.

**Comment by scriptmode** [comment]
Ah, thanks. Missed the short-syntax, because it's not part of the documentation.
