### ISSUE TITLE
Python modules not found on Ubuntu

### ISSUE THREAD

**Issue by annargrs** [konodyuk/obsidian-text-expander#4]
I am trying to get the text expander to run a simple no-arguments python script with the following config:

```
	{"regex": "^foo$",
	"command": "python3 <scripts_path>/bar.py"
	}
```
The `bar.py` file has the following shebang line: `#!/usr/bin/python3`

`python3 <scripts_path>/bar.py` runs fine if executed in the terminal (Ubuntu 20.04), where `which python3` points to the same `/usr/bin/python3`. But the text expander execution fails, because python cannot find the required modules (which have been pip3-installed system-wide).

I thought that maybe it somehow calls some different python binary, but the expander command `{{shell: which python3}}` also outputs `/usr/bin/python3`, as expected.

Obsidian was installed via flathub.

**Comment by konodyuk** [comment]
It is a somewhat known issue. You could start by explicitly specifying the path to the python executable, `/usr/bin/python3 <scripts_path>/bar.py` in your case.

**Comment by annargrs** [comment]
Yeah, I tried that. Same result :(

**Comment by annargrs** [comment]
So... is there any way to get Python package installations to work? Do you happen to know why this is happening, and is it a Linux-specific issue? Your extension would have be perfect for integrating Python scripts right in the notes, but not if it involves having to reimplement pandas...

**Comment by konodyuk** [comment]
I think the easiest way to fix it is to modify PYTHONPATH right in your script.
1. Run `python3 -c "import pandas; print(pandas.__file__)"` in your shell to get the location of pandas. You'll get something like `.../site-packages/pandas/__init__.py`
2. Add the following line to the top of your script: `import sys; sys.path.insert(0, ".../site-packages")`, where the string is the parent path of `pandas` directory from the first step.

BTW, the 2.0 version of the plugin will be more python-focused. Check out the [sample script](https://github.com/konodyuk/obsidian-text-expander/blob/master/examples/scripts/main.py).

**Comment by annargrs** [comment]
Hmm, still no luck even with this import. The shell points to the packages in /home/user/.local/lib/python3.x.

**Comment by annargrs** [comment]
Not sure what changed, but it does work now. Thanks for your help!
