### ISSUE TITLE
[question] double quote issue on command

### ISSUE THREAD

**Issue by imtaehyun** [konodyuk/obsidian-text-expander#5]
I want to get text like `## 2021.04.07 (Wed)` using this command:
```
today_str=`date +"%Y.%m.%d (%a)"` && echo "## $today_str"
```
But, I'm not sure how should I put this command in the configuration. 
Specifically, how can I use double quotation mark in double quote?

```bash
{
    "regex": "^standup$",
    "command": "today_str=`date +"%Y.%m.%d (%a)"` && echo "## $today_str""
}
```

Thanks

**Comment by konodyuk** [comment]
Hello, have you tried putting a backslash in front of each of the internal double quotes? In your case it would be like:
```json
{
    "regex": "^standup$",
    "command": "today_str=`date +\"%Y.%m.%d (%a)\"` && echo \"## $today_str\""
}
```

**Comment by imtaehyun** [comment]
It works! Thanks!
