### ISSUE TITLE
Documentation for writing custom tools in Python

### ISSUE THREAD

**Issue by heldinz** [konodyuk/obsidian-text-expander#7]
Thanks for this plugin! It looks to be exactly what I need. Unfortunately I'm having trouble following the examples. It seems the API for custom tools changed recently and I'm unsure what should be specified in the plugin's settings and what should be in the `<scripts_path>` folder.

For example, the default settings for the `tool:` and `sympy:` triggers still reference separate non-existent files (`<scripts_path>/tool.py` and `<scripts_path>/sympy_tool.py` respectively). They also use the `cut` command to manually trim the trigger from the rest of the input text.

The new example script is called `main.py` and seems to not only implement the `sympy` example but to re-implement the `now` command from the default settings too. The `cut_prefix` argument suggests to me that it is no longer required to trim triggers from the `command` specified in the settings but I can't be sure. I'm also unsure if I can just add new triggers by adding new handlers decorated with `@handler.command` or if I also need to modify the `Processor` or `Handler` classes.

Also, the gif moves far too quickly for me to see what's really happening. I'd really appreciate some clear text documentation in the README on the best way to add my own commands, and what the relationship between the settings and any script files is 🙏🏻

**Comment by konodyuk** [comment]
You correctly mentioned that the API was changed. It just hasn't been released yet. Thus, the repository currently reflects the new API and new examples, but the version which can be installed in Obsidian requires old examples which can be found at the [following point in history](https://github.com/konodyuk/obsidian-text-expander/tree/ffaffa4002dbb51fc5e716293ae5a873d66c650d). Of course, I shouldn't have overwritten that folder until the new API is released, but I hope this will happen soon.

**Comment by heldinz** [comment]
Thanks for clarifying! I've now got what it working the way I wanted.
