### ISSUE TITLE
After hitting tab a new line is created

### ISSUE THREAD

**Issue by capitulinojr** [konodyuk/obsidian-text-expander#8]
Hello!
This is my Text Expander Shortcut:
```
[
	{
		"regex": "^rpc:",
		"command": "echo <text> | cut -c 5- | python3 <scripts_path>/rpc.py"
	}
]
```
And this is rpc.py:
`print("[[" + input().replace(" ", "_") + "]]");`

But when I hit tab, the cursor doesn't stay on the same line (as demo shows), it goes to a new line:

![screencast-00006](https://user-images.githubusercontent.com/13135618/124806278-e6e41c00-df32-11eb-8852-923436b8fadc.gif)

I want it to stay on the same line, as it's most convenient to me.
Can you help me?

**Comment by konodyuk** [comment]
You should use `print(..., end="")` instead of `print(...)`, since it outputs a newline by default.

**Comment by capitulinojr** [comment]
Oh. Right. Thank you so much!
